package br.com.travelmate.model;

import java.util.Date;
import javax.annotation.Generated;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@Generated(value="Dali", date="2018-07-09T13:57:50.531-0300")
@StaticMetamodel(Parametrosprodutos.class)
public class Parametrosprodutos_ {
	public static volatile SingularAttribute<Parametrosprodutos, Integer> idparametrosProdutos;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> visto;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> cursos;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> seguroPrivado;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> vistoOrcamento;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> seguroOrcamento;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> highSchool;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> pacotes;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> programasTeens;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> passagem;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> passagemTaxa;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> passagemTaxaTM;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> ladies;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> aupair;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> work;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> fornecedor;
	public static volatile SingularAttribute<Parametrosprodutos, String> emailCambio01;
	public static volatile SingularAttribute<Parametrosprodutos, String> emailCambio02;
	public static volatile SingularAttribute<Parametrosprodutos, String> emailCambio03;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> passagemTarifa;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> seguroGovernamental;
	public static volatile SingularAttribute<Parametrosprodutos, Float> valorTaxaTM;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> trainee;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> voluntariado;
	public static volatile SingularAttribute<Parametrosprodutos, String> emailCotacao;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> descontomatriz;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> idplanocontas;
	public static volatile SingularAttribute<Parametrosprodutos, Float> cartao01;
	public static volatile SingularAttribute<Parametrosprodutos, Float> cartao02;
	public static volatile SingularAttribute<Parametrosprodutos, Float> cartao07;
	public static volatile SingularAttribute<Parametrosprodutos, Float> boletos;
	public static volatile SingularAttribute<Parametrosprodutos, Float> juros;
	public static volatile SingularAttribute<Parametrosprodutos, Float> cartaodebito;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> descontoloja;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> clientepacote;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> fornecedorpacote;
	public static volatile SingularAttribute<Parametrosprodutos, Float> percentualremessa;
	public static volatile SingularAttribute<Parametrosprodutos, Boolean> remessaativa;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> produtoremessa;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> suplementocurso;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> suplementoacomodacao;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> suplementoidade;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> promocaoescola;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> promocaoescolaacomodacao;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> taxatmorcamento;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> produtoextra;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> codescontoloja;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> codescontomatriz;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> copromocaoescola;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> coseguroprivado;
	public static volatile SingularAttribute<Parametrosprodutos, Long> tempologado;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> pctransferencia;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> demipair;
	public static volatile SingularAttribute<Parametrosprodutos, Date> datainiciowork;
	public static volatile SingularAttribute<Parametrosprodutos, String> numeroupload;
	public static volatile SingularAttribute<Parametrosprodutos, String> tamanhoupload;
	public static volatile SingularAttribute<Parametrosprodutos, String> tipoupload;
	public static volatile SingularAttribute<Parametrosprodutos, String> caminhoimagens;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> escolaracer;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> highereducation;
	public static volatile SingularAttribute<Parametrosprodutos, Float> assessoriatmhe;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> idtaxainscricaohe;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> suplementomenoridadeacomodacao;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> tempomensagens;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> descontofornecedor;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> regracursofinalizar;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> segurocancelamentoid;
	public static volatile SingularAttribute<Parametrosprodutos, Integer> traducaojuramentada;
	public static volatile SingularAttribute<Parametrosprodutos, String> pacoteespecialimg;
}
