package br.com.travelmate.model;

import java.util.Date;
import javax.annotation.Generated;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@Generated(value="Dali", date="2018-03-01T21:10:40.306-0300")
@StaticMetamodel(Voluntariado.class)
public class Voluntariado_ {
	public static volatile SingularAttribute<Voluntariado, Integer> idvoluntariado;
	public static volatile SingularAttribute<Voluntariado, String> idiomaEstudar;
	public static volatile SingularAttribute<Voluntariado, String> nivelIdiomaEstudar;
	public static volatile SingularAttribute<Voluntariado, String> nomeContatoEmergencia;
	public static volatile SingularAttribute<Voluntariado, String> foneContatoEmergencia;
	public static volatile SingularAttribute<Voluntariado, String> emailContatoEmergencia;
	public static volatile SingularAttribute<Voluntariado, String> relacaoContatoEmergencia;
	public static volatile SingularAttribute<Voluntariado, String> instituicaoEstuda;
	public static volatile SingularAttribute<Voluntariado, String> cursoEstuda;
	public static volatile SingularAttribute<Voluntariado, String> duracaoCursoEstuda;
	public static volatile SingularAttribute<Voluntariado, String> periodoCursoEstuda;
	public static volatile SingularAttribute<Voluntariado, Date> dataMatriculaCursoEstuda;
	public static volatile SingularAttribute<Voluntariado, Date> dataEstimadaTerminoCursoEstuda;
	public static volatile SingularAttribute<Voluntariado, String> profissao;
	public static volatile SingularAttribute<Voluntariado, String> cargo;
	public static volatile SingularAttribute<Voluntariado, String> descricaoCargo;
	public static volatile SingularAttribute<Voluntariado, String> outrasHabilidade;
	public static volatile SingularAttribute<Voluntariado, String> curso;
	public static volatile SingularAttribute<Voluntariado, Integer> aulasporSemana;
	public static volatile SingularAttribute<Voluntariado, Integer> numeroSemanas;
	public static volatile SingularAttribute<Voluntariado, Date> dataInicio;
	public static volatile SingularAttribute<Voluntariado, Date> dataTermino;
	public static volatile SingularAttribute<Voluntariado, String> tipoAcomodacao;
	public static volatile SingularAttribute<Voluntariado, Integer> numeroSemanasAcomodacao;
	public static volatile SingularAttribute<Voluntariado, String> tipoQuarto;
	public static volatile SingularAttribute<Voluntariado, String> refeicoes;
	public static volatile SingularAttribute<Voluntariado, String> adicionais;
	public static volatile SingularAttribute<Voluntariado, Date> dataChegadaAcomodacao;
	public static volatile SingularAttribute<Voluntariado, Date> dataPartidaAcomodacao;
	public static volatile SingularAttribute<Voluntariado, String> familiaCrianca;
	public static volatile SingularAttribute<Voluntariado, String> familiaAnimais;
	public static volatile SingularAttribute<Voluntariado, String> fumante;
	public static volatile SingularAttribute<Voluntariado, String> vegetariano;
	public static volatile SingularAttribute<Voluntariado, String> hobbies;
	public static volatile SingularAttribute<Voluntariado, String> possuiAlergia;
	public static volatile SingularAttribute<Voluntariado, String> quaisAlergias;
	public static volatile SingularAttribute<Voluntariado, String> solicitacoesEspeciais;
	public static volatile SingularAttribute<Voluntariado, String> transferin;
	public static volatile SingularAttribute<Voluntariado, String> transferout;
	public static volatile SingularAttribute<Voluntariado, Date> dataChegadaTransfer;
	public static volatile SingularAttribute<Voluntariado, String> voo;
	public static volatile SingularAttribute<Voluntariado, String> ciaerea;
	public static volatile SingularAttribute<Voluntariado, String> horario;
	public static volatile SingularAttribute<Voluntariado, String> projetoVoluntariado;
	public static volatile SingularAttribute<Voluntariado, Date> dataInicioVoluntariado;
	public static volatile SingularAttribute<Voluntariado, Date> dataTerminoVoluntariado;
	public static volatile SingularAttribute<Voluntariado, String> experienciaVoluntariado;
	public static volatile SingularAttribute<Voluntariado, String> motivoVoluntariado;
	public static volatile SingularAttribute<Voluntariado, String> deficienciaFisica;
	public static volatile SingularAttribute<Voluntariado, String> possuiProblemaSaude;
	public static volatile SingularAttribute<Voluntariado, String> descricaoProblemaSaude;
	public static volatile SingularAttribute<Voluntariado, String> tratamentoMedico;
	public static volatile SingularAttribute<Voluntariado, String> descricaoMedico;
	public static volatile SingularAttribute<Voluntariado, String> tratamentoDrogas;
	public static volatile SingularAttribute<Voluntariado, String> descricaoDrogas;
	public static volatile SingularAttribute<Voluntariado, String> fezCirurgia;
	public static volatile SingularAttribute<Voluntariado, String> descricaoCirurgia;
	public static volatile SingularAttribute<Voluntariado, String> dietaEspecifica;
	public static volatile SingularAttribute<Voluntariado, String> cartaoVTM;
	public static volatile SingularAttribute<Voluntariado, String> numerocartaoVTM;
	public static volatile SingularAttribute<Voluntariado, String> meodaCartaoVTM;
	public static volatile SingularAttribute<Voluntariado, String> seguroViagem;
	public static volatile SingularAttribute<Voluntariado, String> seguradora;
	public static volatile SingularAttribute<Voluntariado, String> planoSeguro;
	public static volatile SingularAttribute<Voluntariado, Date> dataInicioSeguro;
	public static volatile SingularAttribute<Voluntariado, Date> dataTerminoSeguro;
	public static volatile SingularAttribute<Voluntariado, Integer> numeroSemanasSeguro;
	public static volatile SingularAttribute<Voluntariado, String> passagemAerea;
	public static volatile SingularAttribute<Voluntariado, String> observacaoPassagem;
	public static volatile SingularAttribute<Voluntariado, String> vistoConsular;
	public static volatile SingularAttribute<Voluntariado, String> observacaoVistoConsultar;
	public static volatile SingularAttribute<Voluntariado, Date> dataEntregaDocumentoVisto;
	public static volatile SingularAttribute<Voluntariado, String> nivelFitness;
	public static volatile SingularAttribute<Voluntariado, String> controle;
	public static volatile SingularAttribute<Voluntariado, Vendas> vendas;
	public static volatile SingularAttribute<Voluntariado, Boolean> habilitarCurso;
}
