package br.com.travelmate.model;

import java.util.Date;
import javax.annotation.Generated;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@Generated(value="Dali", date="2018-03-01T21:10:40.312-0300")
@StaticMetamodel(Worktravel.class)
public class Worktravel_ {
	public static volatile SingularAttribute<Worktravel, Integer> idworkTravel;
	public static volatile SingularAttribute<Worktravel, String> tipo;
	public static volatile SingularAttribute<Worktravel, String> nomeContatoEmergencia;
	public static volatile SingularAttribute<Worktravel, String> foneContatoEmergencia;
	public static volatile SingularAttribute<Worktravel, String> emailContatoEmergencia;
	public static volatile SingularAttribute<Worktravel, String> relacaoContatoEmergencia;
	public static volatile SingularAttribute<Worktravel, String> intituicaoEstuda;
	public static volatile SingularAttribute<Worktravel, String> cursoEstuda;
	public static volatile SingularAttribute<Worktravel, String> duracaoCurso;
	public static volatile SingularAttribute<Worktravel, String> periodoCurso;
	public static volatile SingularAttribute<Worktravel, String> peirodoEstuda;
	public static volatile SingularAttribute<Worktravel, Date> dataMatricula;
	public static volatile SingularAttribute<Worktravel, Date> dataEstimadaTermino;
	public static volatile SingularAttribute<Worktravel, String> idioma01;
	public static volatile SingularAttribute<Worktravel, String> nivelidioma01;
	public static volatile SingularAttribute<Worktravel, String> tempoidioma01;
	public static volatile SingularAttribute<Worktravel, String> idioma02;
	public static volatile SingularAttribute<Worktravel, String> nivelidioma02;
	public static volatile SingularAttribute<Worktravel, String> tempoidioma02;
	public static volatile SingularAttribute<Worktravel, String> idioma03;
	public static volatile SingularAttribute<Worktravel, String> nivelidioma03;
	public static volatile SingularAttribute<Worktravel, String> tempoidioma03;
	public static volatile SingularAttribute<Worktravel, Date> dataInicioPretendida01;
	public static volatile SingularAttribute<Worktravel, Date> dataInicioPretendida02;
	public static volatile SingularAttribute<Worktravel, Date> dataTerminoPretendida01;
	public static volatile SingularAttribute<Worktravel, Date> dataTerminoPretendida02;
	public static volatile SingularAttribute<Worktravel, Boolean> camareira;
	public static volatile SingularAttribute<Worktravel, Boolean> cozinha;
	public static volatile SingularAttribute<Worktravel, Boolean> salvavidas;
	public static volatile SingularAttribute<Worktravel, Boolean> recepcao;
	public static volatile SingularAttribute<Worktravel, Boolean> garcon;
	public static volatile SingularAttribute<Worktravel, Boolean> trabalhosexternos;
	public static volatile SingularAttribute<Worktravel, Boolean> lavadeira;
	public static volatile SingularAttribute<Worktravel, Boolean> indiferenteocupacao;
	public static volatile SingularAttribute<Worktravel, Boolean> outraocupacao;
	public static volatile SingularAttribute<Worktravel, String> especificarOutraOcupacao;
	public static volatile SingularAttribute<Worktravel, Boolean> programaidependente;
	public static volatile SingularAttribute<Worktravel, Boolean> parquetematico;
	public static volatile SingularAttribute<Worktravel, Boolean> hotel;
	public static volatile SingularAttribute<Worktravel, Boolean> restaurante;
	public static volatile SingularAttribute<Worktravel, Boolean> lojas;
	public static volatile SingularAttribute<Worktravel, Boolean> cassino;
	public static volatile SingularAttribute<Worktravel, Boolean> piscina;
	public static volatile SingularAttribute<Worktravel, Boolean> estacaoesqui;
	public static volatile SingularAttribute<Worktravel, Boolean> indiferentelocal;
	public static volatile SingularAttribute<Worktravel, Boolean> outrolocal;
	public static volatile SingularAttribute<Worktravel, String> especificaroutraLocal;
	public static volatile SingularAttribute<Worktravel, Boolean> programaodependente01;
	public static volatile SingularAttribute<Worktravel, String> clima;
	public static volatile SingularAttribute<Worktravel, String> adicionais;
	public static volatile SingularAttribute<Worktravel, String> sabernadar;
	public static volatile SingularAttribute<Worktravel, String> treinamentosalvavidas;
	public static volatile SingularAttribute<Worktravel, String> sabeesquiar;
	public static volatile SingularAttribute<Worktravel, String> carteiraHabilitacao;
	public static volatile SingularAttribute<Worktravel, String> dirigirEua;
	public static volatile SingularAttribute<Worktravel, String> nomePais01;
	public static volatile SingularAttribute<Worktravel, String> motivoEstadia01;
	public static volatile SingularAttribute<Worktravel, String> periodoEstadia01;
	public static volatile SingularAttribute<Worktravel, String> nomePais02;
	public static volatile SingularAttribute<Worktravel, String> motivoEstadia02;
	public static volatile SingularAttribute<Worktravel, String> periodoEstadia02;
	public static volatile SingularAttribute<Worktravel, String> nomePais03;
	public static volatile SingularAttribute<Worktravel, String> motivoEstadia03;
	public static volatile SingularAttribute<Worktravel, String> peirodoEstadia03;
	public static volatile SingularAttribute<Worktravel, String> campanheiroViagem01;
	public static volatile SingularAttribute<Worktravel, String> companheiroViagem02;
	public static volatile SingularAttribute<Worktravel, String> companheiroViagem03;
	public static volatile SingularAttribute<Worktravel, String> trabalhoVistoJ1;
	public static volatile SingularAttribute<Worktravel, String> quantoVistoj1;
	public static volatile SingularAttribute<Worktravel, String> numeroSocialSecurity;
	public static volatile SingularAttribute<Worktravel, String> tipoProgramaEua;
	public static volatile SingularAttribute<Worktravel, String> agenciaBrasil;
	public static volatile SingularAttribute<Worktravel, String> posicaoExcercida;
	public static volatile SingularAttribute<Worktravel, String> opcaoIndependente;
	public static volatile SingularAttribute<Worktravel, String> possuiOfertaTrabalho;
	public static volatile SingularAttribute<Worktravel, String> nomeEmpregador;
	public static volatile SingularAttribute<Worktravel, String> possicarqueiraExercer;
	public static volatile SingularAttribute<Worktravel, String> possuiDeficienciaFisica;
	public static volatile SingularAttribute<Worktravel, String> problemaSaude;
	public static volatile SingularAttribute<Worktravel, String> especifiqueProblemaSaude;
	public static volatile SingularAttribute<Worktravel, String> tratamentoMedico;
	public static volatile SingularAttribute<Worktravel, String> especifiqueTratamentoMedico;
	public static volatile SingularAttribute<Worktravel, String> tratamentoUsoDrogas;
	public static volatile SingularAttribute<Worktravel, String> especifiqueTratamentoUsoDrogas;
	public static volatile SingularAttribute<Worktravel, String> listaAlergias;
	public static volatile SingularAttribute<Worktravel, String> cartaoVTM;
	public static volatile SingularAttribute<Worktravel, String> numeroCartaoVTM;
	public static volatile SingularAttribute<Worktravel, String> moedaCartaoVTM;
	public static volatile SingularAttribute<Worktravel, String> passagemAerea;
	public static volatile SingularAttribute<Worktravel, String> tipoEmissaoPassagem;
	public static volatile SingularAttribute<Worktravel, String> observacaoPassagem;
	public static volatile SingularAttribute<Worktravel, String> tipoVisto;
	public static volatile SingularAttribute<Worktravel, String> tipoEmissaoVisto;
	public static volatile SingularAttribute<Worktravel, String> observacaoVisto;
	public static volatile SingularAttribute<Worktravel, Date> dataEntragaDocumentosVisto;
	public static volatile SingularAttribute<Worktravel, String> fuma;
	public static volatile SingularAttribute<Worktravel, Date> dataInscricao;
	public static volatile SingularAttribute<Worktravel, String> controle;
	public static volatile SingularAttribute<Worktravel, String> obstm;
	public static volatile SingularAttribute<Worktravel, String> inicioPrevisto;
	public static volatile SingularAttribute<Worktravel, String> skype;
	public static volatile SingularAttribute<Worktravel, Valoreswork> valoreswork;
	public static volatile SingularAttribute<Worktravel, Vendas> vendas;
}
